### PR TITLE
Fix parsing of git rev-parse output

### LINKED ISSUE #884: Fails when branch has `=` character
Steps to reproduce:

```
git checkout -b some@weird=branch-name
tig
```

### PR DESCRIPTION
**Pull request by koutcher**
Closes #884

### CODE REVIEW

File: src/repo.c [hunk 1]
```diff
@@ -80,7 +80,7 @@ reload_repo_info(const char **rev_parse_argv)
 {
 	struct repo_info_state state = { rev_parse_argv + 2 };
 
-	return io_run_load(rev_parse_argv, "=", read_repo_info, &state);
+	return io_run_load(rev_parse_argv, "\n", read_repo_info, &state);
```
Comment (jonas) [inline src/repo.c]: :+1: Values are per line without any key.
